server:
  port: 8083
eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8010/eureka
    fetch-registry: true

spring:
  application:
    #服务在注册中心的名称 不同服务名称不能重复
    name: cloud-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application

